Repository AthennaMind/opnsense-exporter, pull requests merged in 2024-03, with the labels that each got.

#7 FEATURE: add file envs for secrets
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  internal/collector/collector_test.go
  internal/options/collectors.go
  internal/options/exporter.go
  internal/options/init.go
  internal/options/log.go
  internal/options/ops.go
  internal/options/ops_test.go
  main.go
  opnsense/client.go
Labels: enhancement, security

#9 FEATURE: implement tcp stats metrics
  .github/pull_request_template.md
  internal/collector/protocol.go
  internal/options/ops.go
  opnsense/protocol_statistics.go
  opnsense/unbound_dns.go
Labels: enhancement, new metrics

#14 FEATURE: implement unbound DNS disable switch
  README.md
  internal/collector/arp_table.go
  internal/collector/collector.go
  internal/collector/collector_test.go
  internal/collector/cron.go
  internal/collector/gateways.go
  internal/collector/interfaces.go
  internal/collector/openvpn.go
  internal/collector/protocol.go
  internal/collector/services.go
  internal/collector/unbound_dns.go
  internal/collector/utils.go
  internal/collector/wireguard.go
  internal/options/collectors.go
  internal/options/ops_test.go
  main.go
Labels: enhancement, good first issue

#15 DOCS: Add metrics list
  .github/pull_request_template.md
  README.md
  docs/metrics.md
Labels: documentation, good first issue

#11 Changes CMD for ENTRYPOINT
  Dockerfile
  README.md
Labels: bug, documentation

#13 feat: adds basic k8s deployment
  README.md
  deploy/k8s/deployment.yaml
  deploy/k8s/readme.md
  deploy/k8s/scrape.yaml
Labels: documentation, good first issue, ci/cd
